name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '20'
  BUN_VERSION: '1.2.16'

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Extract model types
        run: bun src/extract-model-types.ts

      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet src/ai-models.ts; then
            echo "has-changes=false" >> $GITHUB_OUTPUT
            echo "✅ No model changes detected"
          else
            echo "has-changes=true" >> $GITHUB_OUTPUT
            echo "ℹ️  Model changes detected (will not be committed in CI)"
          fi

      - name: Type check
        run: bun run typecheck

      - name: Run unit tests
        run: bun run test:unit

      - name: Build package
        run: bun run bundle

      - name: Run integration tests
        run: bun run test:integration-only

      - name: Test package imports
        run: |
          echo "Testing CommonJS import..."
          node -e "
            const pkg = require('./dist/index.cjs');
            console.log('✅ CJS import successful');
            console.log('Providers:', pkg.getProviders().length);
            console.log('Models:', pkg.ALL_MODELS.length);
            console.log('Categories:', pkg.getCategories().length);
          "

          echo "Testing ESM import..."
          node -e "
            import('./dist/index.js').then(pkg => {
              console.log('✅ ESM import successful');
              console.log('Providers:', pkg.getProviders().length);
              console.log('Models:', pkg.ALL_MODELS.length);
              console.log('Categories:', pkg.getCategories().length);
            });
          "

      - name: Summary
        run: |
          echo "🎉 CI Pipeline completed successfully!"
          echo "✅ All tests passed"
          echo "✅ Build artifacts generated"
          echo "✅ Package imports verified"
          if [ "${{ steps.check-changes.outputs.has-changes }}" == "true" ]; then
            echo "ℹ️  Model changes detected - push to main branch to trigger publish workflow"
          else
            echo "ℹ️  No model changes detected"
          fi